services:
  backend:
    build: ./backend
    image: ghcr.io/brandoluu/horse-backend-windows:latest
    platform: linux/amd64
    ports:
      - "8000:8000"           # Expose backend to LAN
    networks:
      - horse_prediction_network
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped   # optional: restart if it crashes

  frontend:
    build: ./frontend
    image: ghcr.io/brandoluu/horse-frontend-windows:latest
    platform: linux/amd64
    ports:
      - "3000:3000"           # Expose frontend to LAN
    networks:
      - horse_prediction_network
    restart: unless-stopped

networks:
  horse_prediction_network:
    driver: bridge
